version: '3.9'
services:
  cn_privacy_def_idm_atk_cen_ess1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_cen
    - ess=1
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_cen_ess1:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_cen_ess10:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_cen
    - ess=10
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_cen_ess10:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_cen_ess100:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_cen
    - ess=100
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_cen_ess100:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_cen_ess1000:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_cen
    - ess=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_cen_ess1000:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_ent_ess1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_ent
    - ess=1
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_ent_ess1:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_ent_ess10:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_ent
    - ess=10
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_ent_ess10:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_ent_ess100:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_ent
    - ess=100
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_ent_ess100:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_ent_ess1000:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_ent
    - ess=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_ent_ess1000:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_mle_ess1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_mle
    - ess=1
    - n_bns=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_mle_ess1:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_mle_ess10:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_mle
    - ess=10
    - n_bns=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_mle_ess10:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_mle_ess100:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_mle
    - ess=100
    - n_bns=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_mle_ess100:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_mle_ess1000:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_mle
    - ess=1000
    - n_bns=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_mle_ess1000:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_ran_ess1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_ran
    - ess=1
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_ran_ess1:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_ran_ess10:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_ran
    - ess=10
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_ran_ess10:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_ran_ess100:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_ran
    - ess=100
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_ran_ess100:/workspace/experiments/cn_privacy/output
  cn_privacy_def_idm_atk_ran_ess1000:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_idm
    - atk_mec=atk_ran
    - ess=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_idm_atk_ran_ess1000:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_cen_delta0.1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_cen
    - delta=0.1
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_cen_delta0.1:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_cen_delta0.3:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_cen
    - delta=0.3
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_cen_delta0.3:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_cen_delta0.5:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_cen
    - delta=0.5
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_cen_delta0.5:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_cen_delta0.7:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_cen
    - delta=0.7
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_cen_delta0.7:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_cen_delta1.0:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_cen
    - delta=1.0
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_cen_delta1.0:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ent_delta0.1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ent
    - delta=0.1
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ent_delta0.1:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ent_delta0.3:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ent
    - delta=0.3
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ent_delta0.3:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ent_delta0.5:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ent
    - delta=0.5
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ent_delta0.5:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ent_delta0.7:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ent
    - delta=0.7
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ent_delta0.7:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ent_delta1.0:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ent
    - delta=1.0
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ent_delta1.0:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_mle_delta0.1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_mle
    - delta=0.1
    - n_bns=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_mle_delta0.1:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_mle_delta0.3:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_mle
    - delta=0.3
    - n_bns=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_mle_delta0.3:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_mle_delta0.5:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_mle
    - delta=0.5
    - n_bns=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_mle_delta0.5:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_mle_delta0.7:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_mle
    - delta=0.7
    - n_bns=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_mle_delta0.7:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_mle_delta1.0:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_mle
    - delta=1.0
    - n_bns=1000
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_mle_delta1.0:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ran_delta0.1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ran
    - delta=0.1
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ran_delta0.1:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ran_delta0.3:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ran
    - delta=0.3
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ran_delta0.3:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ran_delta0.5:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ran
    - delta=0.5
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ran_delta0.5:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ran_delta0.7:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ran
    - delta=0.7
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ran_delta0.7:/workspace/experiments/cn_privacy/output
  cn_privacy_def_ran_atk_ran_delta1.0:
    build: .
    command:
    - python
    - -m
    - experiments.cn_privacy.exp
    - def_mec=def_ran
    - atk_mec=atk_ran
    - delta=1.0
    image: bnp:2025
    volumes:
    - ./experiments/cn_privacy/bns:/workspace/experiments/cn_privacy/bns
    - ./experiments/cn_privacy/data:/workspace/experiments/cn_privacy/data
    - ./experiments/cn_privacy/output_def_ran_atk_ran_delta1.0:/workspace/experiments/cn_privacy/output
