version: '3.9'
services:
  cn_vs_noisybn_def_idm_atk_ran_ess1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_vs_noisybn.exp
    - def_mec=def_idm
    - atk_mec=atk_ran
    - ess=1
    image: bnp:2025
    volumes:
    - ./experiments/cn_vs_noisybn/bns:/workspace/experiments/cn_vs_noisybn/bns
    - ./experiments/cn_vs_noisybn/data:/workspace/experiments/cn_vs_noisybn/data
    - ./experiments/cn_vs_noisybn/output_def_idm_atk_ran_ess1:/workspace/experiments/cn_vs_noisybn/output
  cn_vs_noisybn_def_idm_atk_ran_ess100:
    build: .
    command:
    - python
    - -m
    - experiments.cn_vs_noisybn.exp
    - def_mec=def_idm
    - atk_mec=atk_ran
    - ess=100
    image: bnp:2025
    volumes:
    - ./experiments/cn_vs_noisybn/bns:/workspace/experiments/cn_vs_noisybn/bns
    - ./experiments/cn_vs_noisybn/data:/workspace/experiments/cn_vs_noisybn/data
    - ./experiments/cn_vs_noisybn/output_def_idm_atk_ran_ess100:/workspace/experiments/cn_vs_noisybn/output
  cn_vs_noisybn_def_idm_atk_ran_ess50:
    build: .
    command:
    - python
    - -m
    - experiments.cn_vs_noisybn.exp
    - def_mec=def_idm
    - atk_mec=atk_ran
    - ess=50
    image: bnp:2025
    volumes:
    - ./experiments/cn_vs_noisybn/bns:/workspace/experiments/cn_vs_noisybn/bns
    - ./experiments/cn_vs_noisybn/data:/workspace/experiments/cn_vs_noisybn/data
    - ./experiments/cn_vs_noisybn/output_def_idm_atk_ran_ess50:/workspace/experiments/cn_vs_noisybn/output
  cn_vs_noisybn_def_ran_atk_ran_delta0.001:
    build: .
    command:
    - python
    - -m
    - experiments.cn_vs_noisybn.exp
    - def_mec=def_ran
    - atk_mec=atk_ran
    - delta=0.001
    image: bnp:2025
    volumes:
    - ./experiments/cn_vs_noisybn/bns:/workspace/experiments/cn_vs_noisybn/bns
    - ./experiments/cn_vs_noisybn/data:/workspace/experiments/cn_vs_noisybn/data
    - ./experiments/cn_vs_noisybn/output_def_ran_atk_ran_delta0.001:/workspace/experiments/cn_vs_noisybn/output
  cn_vs_noisybn_def_ran_atk_ran_delta0.05:
    build: .
    command:
    - python
    - -m
    - experiments.cn_vs_noisybn.exp
    - def_mec=def_ran
    - atk_mec=atk_ran
    - delta=0.05
    image: bnp:2025
    volumes:
    - ./experiments/cn_vs_noisybn/bns:/workspace/experiments/cn_vs_noisybn/bns
    - ./experiments/cn_vs_noisybn/data:/workspace/experiments/cn_vs_noisybn/data
    - ./experiments/cn_vs_noisybn/output_def_ran_atk_ran_delta0.05:/workspace/experiments/cn_vs_noisybn/output
  cn_vs_noisybn_def_ran_atk_ran_delta0.1:
    build: .
    command:
    - python
    - -m
    - experiments.cn_vs_noisybn.exp
    - def_mec=def_ran
    - atk_mec=atk_ran
    - delta=0.1
    image: bnp:2025
    volumes:
    - ./experiments/cn_vs_noisybn/bns:/workspace/experiments/cn_vs_noisybn/bns
    - ./experiments/cn_vs_noisybn/data:/workspace/experiments/cn_vs_noisybn/data
    - ./experiments/cn_vs_noisybn/output_def_ran_atk_ran_delta0.1:/workspace/experiments/cn_vs_noisybn/output
